version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    command: yarn start
